title: Dean Pretorius
description: Welcome to my GitHub Pages site!
theme: minima

# Theme settings
minima:
  skin: dark
  skin_variant: dark

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/