title: Dean Pretorius
description: Welcome to my GitHub Pages site!
# remote_theme: jekyll/minima
theme: minima 

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/